# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogManage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='artlcle',
            new_name='article',
        ),
    ]
