# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogManage', '0002_auto_20171217_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default=10000, max_length=10000),
            preserve_default=False,
        ),
    ]
