# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogManage', '0003_article_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useraccount', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=2)),
                ('birth', models.DateField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
